[build]
  command = "echo 'No build needed'"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200