# Configurações de build do Netlify
[build]
  command = "echo 'No build needed'" # Comando de build (se não houver um processo de build complexo)
  publish = "." # A pasta de publicação é a raiz do projeto

# Configurações de cabeçalhos HTTP
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Desativa o processamento de funções e ativos na pasta admin
# Isso garante que a página do CMS não seja interferida por otimizações do Netlify
[build.processing]
  skip_processing = true # Desativa todo o processamento para este site (pode ser demais, mas é um teste)

[build.processing.html]
  pretty_urls = false
  minify = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.images]
  compress = false
  strip_metadata = false

# Regra para servir o admin/index.html para qualquer rota dentro de /admin/
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200 # Status 200 para que o SPA do CMS possa lidar com suas rotas internas

# Redirecionamento para o convite do Netlify Identity
# Esta regra garante que o link de convite leve para a página do admin
[[redirects]]
  from = "/.netlify/identity/invite"
  to = "/admin/"
  status = 302
  force = true # Usa 'force = true' no netlify.toml em vez de '!'
