# Desativa o processamento de funções e ativos na pasta admin
# Isso garante que a página do CMS não seja interferida por otimizações do Netlify
[build]
  publish = "." # A pasta de publicação é a raiz do projeto

[build.processing]
  skip_processing = true # Desativa todo o processamento para este site (pode ser demais)

[build.processing.html]
  pretty_urls = false
  minify = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.images]
  compress = false
  strip_metadata = false

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Redirecionamento para o convite do Netlify Identity
[[redirects]]
  from = "/.netlify/identity/invite"
  to = "/admin/"
  status = 302
  force = true # Usa 'force = true' no netlify.toml em vez de '!'
