# Desativa o processamento de funções e ativos na pasta admin
# Isso garante que a página do CMS não seja interferida por otimizações do Netlify
[build]
  publish = "." # A pasta de publicação é a raiz do projeto

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Se você já tem um _redirects, mova a regra identity para cá
[[redirects]]
  from = "/.netlify/identity/invite"
  to = "/admin/"
  status = 302!
