backend:
  name: git-gateway
  branch: main

local_backend: true

media_library:
  name: cloudinary
  config:
    cloud_name: dqfkwolc8             # <- do seu dashboard
    api_key: "683915392936961"        # <- do seu dashboard (pública)
    upload_preset: "hcp_site"         # <- se você criou o preset unsigned
    default_transformations:
      - - fetch_format: auto
          quality: auto

# Apenas para preview do Decap; os arquivos reais ficam no Cloudinary
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: "https://homens-hcp.netlify.app"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "dados"
    label: "Dados do Site"
    editor:
      preview: false
    files:

      # -------- SITE (hero, tema, timeline) --------
      - name: "site"
        label: "Site (Hero, Tema, Timeline)"
        file: "data/site.json"
        fields:
          - { label: "Slogan", name: "slogan", widget: "string", required: false }
          - { label: "Lema", name: "lema", widget: "string", required: false }
          - { label: "Hero (imagem de fundo)", name: "hero", widget: "image", required: false }
          - label: "Tema"
            name: "tema"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Opacidade do overlay do hero (0–1)", name: "hero_overlay", widget: "number", value_type: "float", min: 0, max: 1, step: 0.05, default: 0.45 }
          - label: "Linha do tempo (Timeline)"
            name: "timeline"
            widget: "list"
            fields:
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Ano", name: "ano", widget: "string", required: false }
              - { label: "Texto", name: "texto", widget: "text" }

      # -------- HEADER (logo e menu) --------
      - name: "header"
        label: "Header (Logo e Menu)"
        file: "data/header.json"
        fields:
          - { label: "Logo", name: "logo", widget: "image" }
          - label: "Menu"
            name: "menu"
            widget: "list"
            fields:
              - { label: "Texto", name: "text", widget: "string" }
              - { label: "URL (âncora ou link)", name: "url", widget: "string" }

      # -------- FOOTER --------
      - name: "footer"
        label: "Footer"
        file: "data/footer.json"
        fields:
          - { label: "Logo", name: "logo", widget: "image", required: false }
          - { label: "Texto", name: "texto", widget: "string", required: false }
          - label: "Links"
            name: "links"
            widget: "list"
            fields:
              - { label: "Nome", name: "nome", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }

      # -------- COORDENAÇÃO --------
      - name: "coordenacao"
        label: "Coordenação"
        file: "data/coordenacao.json"
        fields:
          - label: "Equipe"
            name: "equipe"
            widget: "list"
            fields:
              - { label: "Nome", name: "nome", widget: "string" }
              - { label: "Cargo", name: "cargo", widget: "string", required: false }
              - { label: "Descrição", name: "descricao", widget: "text", required: false }
              - { label: "Foto (Cloudinary)", name: "foto", widget: "image" }

      # -------- MEMBROS --------
      - name: "membros"
        label: "Membros"
        file: "data/membros.json"
        fields:
          - label: "Membros"
            name: "membros"
            widget: "list"
            fields:
              - { label: "Nome", name: "nome", widget: "string" }
              - { label: "Foto (Cloudinary)", name: "foto", widget: "image" }
              - { label: "Naipe(s)", name: "naipes", widget: "select", multiple: true, options: ["1º Tenor","2º Tenor","Barítono","Baixo"], required: false }
              - { label: "Bio", name: "bio", widget: "text", required: false }

      # -------- GALERIA --------
      - name: "galeria"
        label: "Galeria"
        file: "data/galeria.json"
        fields:
          - label: "Álbuns"
            name: "albuns"
            widget: "list"
            fields:
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Descrição", name: "descricao", widget: "text", required: false }
              - { label: "Capa (Cloudinary)", name: "capa", widget: "image", required: false }
              - label: "Itens"
                name: "itens"
                widget: "list"
                fields:
                  - { label: "Tipo", name: "tipo", widget: "select", options: ["foto","video"], default: "foto" }
                  - { label: "Fonte (URL da imagem ou vídeo)", name: "src", widget: "string" }
                  - { label: "Legenda/alt", name: "alt", widget: "string", required: false }

      # -------- DOAÇÕES --------
      - name: "doacoes"
        label: "Doações"
        file: "data/doacoes.json"
        fields:
          - { label: "Meta total (R$)", name: "meta_total", widget: "number", value_type: "float", required: false }
          - { label: "Arrecadado (R$)", name: "arrecadado", widget: "number", value_type: "float", required: false }
          - { label: "Chave PIX", name: "pix_chave", widget: "string", required: false }
          - { label: "QR Code PIX (imagem)", name: "pix_qr", widget: "image", required: false }
          - label: "Outras formas (links)"
            name: "links"
            widget: "list"
            fields:
              - { label: "Nome", name: "nome", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }

      # -------- CONTATO --------
      - name: "contato"
        label: "Contato"
        file: "data/contato.json"
        fields:
          - { label: "E-mail", name: "email", widget: "string", required: false }
          - { label: "Telefone", name: "telefone", widget: "string", required: false }
          - { label: "Endereço", name: "endereco", widget: "string", required: false }
